[package]
name = "demo"
description = "Demo applications"
version = "0.0.1"
edition = "2024"
authors = ["Andrew Pennebaker <andrew.pennebaker@gmail.com>"]
license = "BSD-2-Clause"

[[bin]]
name = "hello"
path = "src/hello.rs"

[profile.release]
strip = "symbols"
