# debug = true

# Compile musl targets fully static
#
# rustflags."musl" = "-C target-feature=+crt-static"

# All functional, non-mobile, non-embedded cross targets
#
# exclusion_targets = [
#     "android",
#     "arm64ec-pc-windows-msvc",
#     "cuda",
#     "emscripten",
#     "fortanix",
#     "fuchsia",
#     "gnullvm",
#     "gnux32",
#     "i686-pc-windows-gnu",
#     "ios",
#     "loongarch",
#     "none-eabi",
#     "ohos",
#     "pc-solaris",
#     "powerpc64le-unknown-linux-musl",
#     "redox",
#     "riscv64gc-unknown-linux-musl",
#     "sparcv9-sun-solaris",
#     "uefi",
#     "unknown-none",
#     "wasm",
# ]

# Skip GNU targets and 32 bit targets
#
# exclusion_targets = [
#     "android",
#     "arm",
#     "cuda",
#     "emscripten",
#     "fortanix",
#     "fuchsia",
#     "gnu",
#     "i586",
#     "i686",
#     "ios",
#     "loongarch",
#     "none-eabi",
#     "ohos",
#     "pc-solaris",
#     "powerpc64le-unknown-linux-musl",
#     "redox",
#     "riscv64gc-unknown-linux-musl",
#     "sparcv9-sun-solaris",
#     "uefi",
#     "unknown-none",
#     "wasm",
# ]

# exclusion_features = [
#     "letmeout",
# ]

# banner = "<app>-<version>"

# cross_args = []
