# debug = true

#
# Linux Portability
#

rustflags."musl" = "-C target-feature=+crt-static"

exclusion_targets = [
    "android",
    "arm",
    "cuda",
    "emscripten",
    "fortanix",
    "fuchsia",
    "gnu",
    "i586",
    "i686",
    "ios",
    "loongarch",
    "none-eabi",
    "ohos",
    "pc-solaris",
    "powerpc64le-unknown-linux-musl",
    "redox",
    "riscv64gc-unknown-linux-musl",
    "sparcv9-sun-solaris",
    "uefi",
    "unknown-none",
    "wasm",
]
