[target.aarch64-apple-darwin]
image = "aloismisery/aarch64-apple-darwin-cross:extra"

[target.aarch64-pc-windows-msvc]
image = "aloismisery/aarch64-pc-windows-msvc-cross:extra"

[target.x86_64-unknown-netbsd]
pre-build = [
    "mkdir -p /tmp/netbsd",
    "curl -LO https://cdn.netbsd.org/pub/NetBSD/NetBSD-10.1/amd64/binary/sets/base.tar.xz",
    "tar -C /tmp/netbsd -xJf base.tar.xz",
    "cp /tmp/netbsd/usr/lib/libexecinfo.so /usr/local/x86_64-unknown-netbsd/lib",
    "rm base.tar.xz",
    "rm -rf /tmp/netbsd",
]

[target.x86_64-apple-darwin]
image = "aloismisery/x86_64-apple-darwin-cross:extra"

[target.x86_64-pc-windows-msvc]
image = "aloismisery/x86_64-pc-windows-msvc-cross:extra"
